master:    
  file_path: "/tmp/" # in home folder
  
  search_method: "random" # random, grid, fixed, ...
  number_of_sets_to_test: 10000000 # only for random search, 0 for unlimited

  parameters:
    foot_rise:
      min: 0.02
      max: 0.15
      step_size: 0.01
    trunk_roll:
      min: -1
      max: 1
      step_size: 0.1
    trunk_pitch:
      min: -1
      max: 1
      step_size: 0.1
    trunk_yaw:
      min: -1
      max: 1
      step_size: 0.1
    move_trunk_time:
      min: 1
      max: 2
      step_size: 0.1
    raise_foot_time:
      min: 0.2
      max: 1
      step_size: 0.1
    move_to_ball_time:
      min: 0.3
      max: 1.5
      step_size: 0.1
    kick_time:
      min: 0
      max: 0.5
      step_size: 0.05
    move_back_time:
      min: 0
      max: 0.5
      step_size: 0.1
    lower_foot_time:
      min: 0.2
      max: 1
      step_size: 0.1
    move_trunk_back_time:
      min: 0.1
      max: 0.7
      step_size: 0.1
    stabilizing_point_x:
      min: -0.1
      max: 0.05
    stabilizing_point_y:
      min: -0.05
      max: 0.05
